### PR TITLE
Allow fixture names to have deeper extensions

### PR DESCRIPTION
**Pull request by mantasmarcinkus**
Hello,
motivation for the change is most of the time in one single test file I have multiple tests and I want to have separate test fixtures for them, so that I can load specifically, and not loose the table naming convention.
This is not a breaking change and only introduces new functionality. 
**test 1**
```go
fixtures, err := testfixtures.NewFiles(db, &testfixtures.PostgreSQL{},
    "fixtures/favorites#1.yml",
    "fixtures/customers.yml",
)
if err != nil {
    log.Fatal(err)
}
```
**test 2**
```go
fixtures, err := testfixtures.NewFiles(db, &testfixtures.PostgreSQL{},
    "fixtures/favorites#2.yml",
    "fixtures/customers.yml",
)
if err != nil {
    log.Fatal(err)
}
```
Let's discuss. 😄

### CODE REVIEW

**Comment by andreynering** [comment]
Hello @mantasmarcinkus,

Thanks for your patch!

You idea makes sense to me, but I think maybe we should discuss an alternative approach to this use case, because currently it's possible to use `.` to inform the schema of a table.

E.g.: `blog.posts.yml` will insert on `"blog"."posts"` table. (I think we're missing documentation for this).

But I agree we should find a solution to this use case.

**Comment by mantasmarcinkus** [comment]
@andreynering how about #?
Also, it would be awesome if the schema thing would be documented as it a really useful feature 😅

**Comment by mantasmarcinkus** [comment]
Adjusted the PR to use `#` and updated documentation. Hope that travis runs ok, as there is no instructions how to run all the tests properly ❗️

**Comment by andreynering** [comment]
Hi @mantasmarcinkus!

Thanks again for the time you invested on this. I'm sorry but I'll close this PR because of these reasons:

- It's already possible to do this by putting these files in another folder (e.g. `fixtures/alternative/favorites.yml` instead of `fixtures/favorites.yml`). I prefer not having many ways of doing the same thing;
- As an suggestion, you can also have many records in the same file, instead of splitting it in multiple files;
- This may not work well when loading an entire directory, which is what most people do;
- I want to put effort on features (like #24) that might conflict with this in the future.

I'd still be happy to review a PR for improving documentation on support for schemas. Running tests is already [documented here](https://github.com/go-testfixtures/testfixtures#contributing).

**Pull request closed without merging**
