### PR TITLE
Add support for resetting schema-namespaced sequences to PostgreSQL

### PR DESCRIPTION
**Pull request by momer**

### CODE REVIEW

**Comment by andreynering** [comment]
@momer Thank you!

I have a question to you: are also trying to load fixtures in any table in another schema than `public`? I ask because I don't think that's currently possible.

**Comment by momer** [comment]
Hey Andrey, no, thank you - this package has been a big help today!

I lucked out and am only working on the public schema for this project, but will take a look at testfixtures to see if we can get a discussion going around adding that feature if you're into it?

**Comment by andreynering** [comment]
Yes, it think it can be done and it's is not that hard. 

We just have to quote a file of name:

```
my_schema.my_table.yml
```

In the right forma for each dialect:

```
"my_schema"."my_table" # PG, oracle, sqlite
`my_schema`.`my_table` # mysql
[my_schema].[my_table] # sqlserver
```

**Comment by momer** [comment]
Ah ok, sounds good

**Comment by momer** [comment]
@andreynering Needed to make additional changes in order to get this to work on PostgreSQL, adding PR now

**Pull request merged**
